# Drissman Backend

## Application
spring.application.name=drissman-backend
server.port=8080
app.upload.dir=uploads/images

## Redis
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6380}

## PostgreSQL R2DBC
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:drissman}}
spring.r2dbc.username=${DB_USERNAME:drissman}
spring.r2dbc.password=${DB_PASSWORD:drissman_secret}

## PostgreSQL JDBC (for Liquibase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:drissman}}
spring.datasource.username=${DB_USERNAME:drissman}
spring.datasource.password=${DB_PASSWORD:drissman_secret}
spring.datasource.driver-class-name=org.postgresql.Driver

## Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

## JWT
jwt.secret=${JWT_SECRET:bru6mlxlAdHXjhPqTstm4QkPqxe8HSbQN2cVGqEqR77JOHBGfbZxZE7J+5CocGNj}
jwt.expiration=86400000

## Google Auth
google.client.id=${GOOGLE_CLIENT_ID:756146333424-03t1jigdf930gksi3jcojpgn2u5cg64s.apps.googleusercontent.com}

## Logging
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG
logging.level.liquibase=INFO

## Firebase
firebase.storage.bucket-name=drissman-680c4.appspot.com
## Mail Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# REMPLACEZ CE QUI SUIT PAR VOTRE EMAIL ET VOTRE MOT DE PASSE D'APPLICATION GMAIL
spring.mail.username=${SPRING_MAIL_USERNAME:votre.email@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:votre_mot_de_passe_app_gmail}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Mistral AI
mistral.api.key=${MISTRAL_API_KEY:}
mistral.api.url=https://api.mistral.ai/v1/chat/completions

## Kernel Core
kernel.base-url=${KERNEL_BASE_URL:https://kernel-core.yowyob.com}
kernel.client-id=${KERNEL_CLIENT_ID:prod-platform-backend}
kernel.api-key=${KERNEL_API_KEY:VbWi225xzYPoD8rQ2FRniTAqkylh34XYeWxa9HCU}
kernel.tenant-id=${KERNEL_TENANT_ID:11111111-1111-1111-1111-111111111111}
